version: '3.9'

services:
  redisearch:
    image: redis/redis-stack-server:latest
    container_name: redisearch
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - book_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  goapp: 
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${PORT}:3000"
    restart: always
    depends_on:
      redisearch:
        condition: service_healthy  
    networks:
      - book_network
        
volumes:
  redis_data:

networks:
  book_network:
    driver: bridge
